import type { Metadata } from "next";
import "./globals.css";
import { Changa } from "next/font/google";
import { getToken } from "./lib/tokenValidation";
import TokenChecker from "./TokenChecker";
import { User } from "./lib/user";

const changa = Changa({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const access = await getToken("access");
  const refresh = await getToken("refresh");
  const user = await User(access || "");
  console.log(user);

  return (
    <html lang="fa" className={changa.className}>
      <TokenChecker accessToken={access} refreshToken={refresh} />
      <body className="antialiased">{children}</body>
    </html>
  );
}
