import type { Metadata } from "next";
import "./globals.css";
import { Changa } from "next/font/google";
import { getToken } from "./lib/tokenValidation";
import { verifyAndReturnAccessPayload } from "./lib/jwt"; // your decode helper

const changa = Changa({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const access = await getToken("access");

  // 🧠 Decode user data from token if valid
  let decodedUser = null;
  if (access) {
    try {
      const payload = await verifyAndReturnAccessPayload(access);
      decodedUser = payload || null;
    } catch (err) {
      console.error("Error decoding access token:", err);
    }
  }

  return (
    <html lang="fa" className={changa.className}>
      <body className="antialiased">
        {/* 🪄 Embed the decoded user JSON for the client */}
        <script
          id="__USER__"
          type="application/json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(decodedUser || null),
          }}
        />
        {children}
      </body>
    </html>
  );
}
