import type { Metadata } from "next";
import "./globals.css";
import { Changa } from "next/font/google";

const changa = Changa({
  subsets: ["arabic"], // or ["latin", "arabic"] depending on your usage
  weight: ["400", "500", "600", "700"], // optional — available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className={`${changa.className}`}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
